name: Project Column by Issue Label

on:
  issues:
    types: [labeled]
jobs:
  General-Backlog:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.ACTION_PROJECT_COLUMN_BY_ISSUE_LABEL }}"
        project-url: "https://github.com/VampireTechnologyLord/TI-Python-Module/projects/4"
        column-name: "Backlog"
        label-name: "General - Backlog"
  General-To-Do:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.ACTION_PROJECT_COLUMN_BY_ISSUE_LABEL }}"
        project-url: "https://github.com/VampireTechnologyLord/TI-Python-Module/projects/4"
        column-name: "To Do"
        label-name: "General - To Do"
  General-WIP:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.ACTION_PROJECT_COLUMN_BY_ISSUE_LABEL }}"
        project-url: "https://github.com/VampireTechnologyLord/TI-Python-Module/projects/4"
        column-name: "Work in Progress"
        label-name: "General - WIP"
