name: Test Workflow

on:
  workflow_dispatch:
    
jobs:
  
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

  build:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Build
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      run: |
        pip install build
    - name: Build package
      run: python -m build

  publish:
    needs: [install-dependencies, build]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ready Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Ready dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Ready package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
